// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEgJjl3zr2BZvBLmYA5crENqYmvvEj6Ys',
    appId: '1:278738925372:web:ff86595cbac5acdd9e1039',
    messagingSenderId: '278738925372',
    projectId: 'lauft-app',
    authDomain: 'lauft-app.firebaseapp.com',
    storageBucket: 'lauft-app.appspot.com',
    measurementId: 'G-RMMLPZ7C4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4zP-XPdeOOoKLUlo8gmYzzBFhTpCVWdA',
    appId: '1:278738925372:android:60fc42c7950d59099e1039',
    messagingSenderId: '278738925372',
    projectId: 'lauft-app',
    storageBucket: 'lauft-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Aa2CE-Zw__qG60CFgfbP75Fh_G_UKEA',
    appId: '1:278738925372:ios:5ba25fb5440fe4e29e1039',
    messagingSenderId: '278738925372',
    projectId: 'lauft-app',
    storageBucket: 'lauft-app.appspot.com',
    iosClientId: '278738925372-tpvotmihgoebaprht8go0n72nu0phn0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.lauftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Aa2CE-Zw__qG60CFgfbP75Fh_G_UKEA',
    appId: '1:278738925372:ios:4e498e8492c73c8f9e1039',
    messagingSenderId: '278738925372',
    projectId: 'lauft-app',
    storageBucket: 'lauft-app.appspot.com',
    iosClientId: '278738925372-3gvtqicaau4207vjouimhn1vgn083ha3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lauftApp.RunnerTests',
  );
}
